#!/usr/bin/env bash
# Regenerate components/epaper/fonts/fonts.c from system fonts via CoreText.
# Run from anywhere; writes the component file in place.
#
# Why these faces (all stock macOS, nothing to install):
#   Arial Bold  — the two big temperatures and their labels.
#   Arial       — the forecast line (lighter, secondary).
#
# Sizes are chosen by MEASUREMENT via tools/preview, never from metrics tables.
# Font_Big at 44pt gives 32px figures, which lets two temperature rows plus a
# forecast line AND a date line fit 122px of height. 52pt (38px) left room for only
# one small line, which forced the forecast and date to share it and truncate.
# Verify any change with `make run` in
# tools/preview — it asserts every width and vertical budget.
#
# Character ranges are trimmed hard: Font_Big is 13 glyphs, not 95.
set -e
set -o pipefail
cd "$(dirname "$0")"

SUP=/System/Library/Fonts/Supplemental
BOLD="$SUP/Arial Bold.ttf"
REG="$SUP/Arial.ttf"

for f in "$BOLD" "$REG"; do
    [ -f "$f" ] || { echo "missing font: $f" >&2; exit 1; }
done

clang -O2 -Wall -framework CoreText -framework CoreGraphics \
      -framework Foundation -o fontgen fontgen.m

OUT=../../components/epaper/fonts/fonts.cpp

{
    echo "// GENERATED by tools/fontgen/genfonts.sh — do not hand-edit."
    echo "// Regenerate:  ./tools/fontgen/genfonts.sh"
    echo "//"
    echo "// All tables are \`const\` and live in this single translation unit, so they"
    echo "// land in .rodata (flash), not DRAM. Including a font header from two .cpp"
    echo "// files would duplicate the data — don't."
    echo "// Verify with: idf.py size-files | grep -i font"
    echo
    echo '#include "fonts.h"'
    echo
    echo 'namespace epd {'
    # Big temperatures: '-' '.' '/' '0'..'9' == 0x2D..0x39 (13 glyphs).
    # '/' rides along in the range and is used by the forecast hi/lo.
    ./fontgen "$BOLD"        44 45 57  Font_Big
    # Labels (INSIDE / OUTSIDE) and the forecast need printable ASCII.
    ./fontgen "$BOLD"        24 32 126 Font_Label
    ./fontgen "$REG"         20 32 126 Font_Cond
    echo
    echo '}  // namespace epd'
} > "$OUT"

echo "wrote $OUT ($(wc -c < "$OUT") bytes of C)" >&2
