#!/usr/bin/env bash
# Regenerate components/epaper/fonts/fonts.c from system fonts via CoreText.
# Run from anywhere; writes the component file in place.
#
# Why these faces (all stock macOS, nothing to install):
#   Arial Bold  — the clock, the temperature and the date.
#   Arial       — the weather condition line (lighter, secondary).
#
# Clock size was chosen by MEASUREMENT, not from font metrics tables. The binding
# constraint is height (the band between the top edge and the y=76 rule), not
# width, so a condensed face is the wrong trade: Arial Narrow Bold 88pt measured
# only 184px wide for "23:59", wasting 60px of a 244px budget. Arial Bold at 92pt
# is 235px wide at the same 67px figure height — same vertical footprint, much
# heavier strokes, far more legible across a room. 94pt would be 239px, leaving
# too little margin; 96pt overflows.
#
# Character ranges are trimmed hard: the clock face is 11 glyphs, not 95.
set -e
set -o pipefail
cd "$(dirname "$0")"

SUP=/System/Library/Fonts/Supplemental
BOLD="$SUP/Arial Bold.ttf"
REG="$SUP/Arial.ttf"

for f in "$BOLD" "$REG"; do
    [ -f "$f" ] || { echo "missing font: $f" >&2; exit 1; }
done

clang -O2 -Wall -framework CoreText -framework CoreGraphics \
      -framework Foundation -o fontgen fontgen.m

OUT=../../components/epaper/fonts/fonts.cpp

{
    echo "// GENERATED by tools/fontgen/genfonts.sh — do not hand-edit."
    echo "// Regenerate:  ./tools/fontgen/genfonts.sh"
    echo "//"
    echo "// All tables are \`const\` and live in this single translation unit, so they"
    echo "// land in .rodata (flash), not DRAM. Including a font header from two .cpp"
    echo "// files would duplicate the data — don't."
    echo "// Verify with: idf.py size-files | grep -i font"
    echo
    echo '#include "fonts.h"'
    echo
    echo 'namespace epd {'
    # Clock: '0'..'9' and ':' == 0x30..0x3A, exactly 11 glyphs.
    ./fontgen "$BOLD"        92 48 58  Font_Clock
    # Temp: '-' '.' '/' '0'..'9' == 0x2D..0x39. '/' is along for the ride.
    ./fontgen "$BOLD"        38 45 57  Font_Temp
    # Date and condition need printable ASCII.
    ./fontgen "$BOLD"        24 32 126 Font_Date
    ./fontgen "$REG"         20 32 126 Font_Cond
    echo
    echo '}  // namespace epd'
} > "$OUT"

echo "wrote $OUT ($(wc -c < "$OUT") bytes of C)" >&2
